### ISSUE TITLE
Add delay to get around Discord rate limit

### ISSUE THREAD

**Issue by jezevec10** [bhainesva/jstris-leaderboard-changes#4]
When I've added more modes I got this rate limit error on discord webhook:

```
StatusError: Too Many Requests
    at ClientRequest.<anonymous> (/home/jstris/jstris-leaderboard-changes/node_modules/bent/src/nodejs.js:133:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10) {
  statusCode: 429,
  json: [AsyncFunction (anonymous)],
  text: [Function (anonymous)],
  arrayBuffer: [Function (anonymous)],
  headers: {
    date: 'Sun, 22 Nov 2020 04:38:06 GMT',
    'content-type': 'application/json',
    'content-length': '91',
    connection: 'close',
    'retry-after': '1097',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-ratelimit-bucket': '3cd1f278bd0ecaf11e0d2391374c011d',
    'x-ratelimit-limit': '5',
    'x-ratelimit-remaining': '0',
    'x-ratelimit-reset': '1606019888',
    'x-ratelimit-reset-after': '2',
    'x-envoy-upstream-service-time': '13',
    via: '1.1 google',
    'cf-cache-status': 'DYNAMIC',
    'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    'x-content-type-options': 'nosniff',
    server: 'cloudflare'
  }
}
```

Trivial solution would be probably just adding some constant delay between requests. Or it could read the `x-ratelimit` headers from the response and retry the requests accorting to that.

**Comment by jezevec10** [comment]
The solution seems to work well, thanks!
